//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarResonanceDpsAnalysis.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarResonanceDpsAnalysis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] AlimamaShuHeiTi {
            get {
                object obj = ResourceManager.GetObject("AlimamaShuHeiTi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ApplicationIcon_256x256 {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon_256x256", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cancel_hover {
            get {
                object obj = ResourceManager.GetObject("cancel_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cancel_normal {
            get {
                object obj = ResourceManager.GetObject("cancel_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg  xmlns=&quot;http://www.w3.org/2000/svg&quot;  width=&quot;24&quot;  height=&quot;24&quot;  viewBox=&quot;0 0 24 24&quot;  fill=&quot;none&quot;  stroke=&quot;currentColor&quot;  stroke-width=&quot;2&quot;  stroke-linecap=&quot;round&quot;  stroke-linejoin=&quot;round&quot;  class=&quot;icon icon-tabler icons-tabler-outline icon-tabler-chart-bar-popular&quot;&gt;&lt;path stroke=&quot;none&quot; d=&quot;M0 0h24v24H0z&quot; fill=&quot;none&quot;/&gt;&lt;path d=&quot;M3 13a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1z&quot; /&gt;&lt;path d=&quot;M9 9a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1z&quot; /&gt;&lt;path d=&quot;M15 5a1 1 0 0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string data_display {
            get {
                return ResourceManager.GetString("data-display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1755665363494&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;6610&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M872 63.9H154c-19.9 0-36 16.1-36 36L98 794.6V885.6h0.8c5.8 41.9 41.7 74.2 85.2 74.2h708c19.9 0 36-16.1 36-36 0 0-43.7-10.7-43.7-47.7s43.7-52.4 43.7-52.4v-28.4-8.3h-0.2L908 99.9c0-19.9-16.1-36-36-36z m-109.3 248c19.9 0 36-16.1 36-36V107.6h65.8l19.6 679.3H141.9l19.6-679.3h446.4V276c0 19.9 16.1 36 36 36l59.4-30 59.4 29.9z m-111.1-52.8V107.6H755v151.5l-32-16. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string diaryIcon {
            get {
                return ResourceManager.GetString("diaryIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1755061232067&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;25570&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M662.016 361.984V102.4H102.4v519.68h219.648V921.6H921.6V361.984z m-19.968 19.968v220.16H342.016v-220.16z m239.616 499.712H361.984v-239.616h320V401.92h199.68z&quot; p-id=&quot;25571&quot;&gt;&lt;/path&gt;&lt;/svg&gt; 的本地化字符串。
        /// </summary>
        internal static string exclude {
            get {
                return ResourceManager.GetString("exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap flushed_hover {
            get {
                object obj = ResourceManager.GetObject("flushed_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap flushed_normal {
            get {
                object obj = ResourceManager.GetObject("flushed_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap handoff_hover {
            get {
                object obj = ResourceManager.GetObject("handoff_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap handoff_normal {
            get {
                object obj = ResourceManager.GetObject("handoff_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] HarmonyOS_Sans {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] HarmonyOS_Sans_SC_Bold {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_SC_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1755131064483&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;11454&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M512.5 98.29c-227.84 0-412.54 184.7-412.54 412.54s184.7 412.54 412.54 412.54 412.54-184.7 412.54-412.54S740.34 98.29 512.5 98.29z m249.28 661.82c-32.4 32.4-70.1 57.82-112.08 75.58-43.42 18.37-89.59 27.68-137.21 27.68-47.62 0-93.78-9.31-137.2-27.68-41.97-17.75-79.68-43.18-112.08-75.58-32.4-32.4-57.82-70.1-75.58-112.08-18.37-43.42-27.68-89.59-27.68-137.21  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string historicalRecords {
            get {
                return ResourceManager.GetString("historicalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1755130842851&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1025 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;7366&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M779 1024H595V827.6c0-14.4-11.6-26-26-26h-93.2c-14.4 0-26 11.8-26 26V1024H251c-54.8 0-99.4-44.6-99.4-99.4V600.2l-112.2-35-9-9c-26.6-26.6-26.6-69.6 0-96.2L470 20.4c12.8-12.8 29.8-20 48-20s35.2 7 48 20l439.6 439.8c12.8 12.8 20 30 19.8 48 0 18.2-7.2 35.2-20 48l-9 9L878 600.4v324.2c0.2 54.8-44.2 99.4-99 99.4z&quot; p-id=&quot;7367&quot;&gt;&lt;/path&gt;&lt;/svg&gt; 的本地化字符串。
        /// </summary>
        internal static string HomeIcon {
            get {
                return ResourceManager.GetString("HomeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] hp_icon {
            get {
                object obj = ResourceManager.GetObject("hp_icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap left_hover {
            get {
                object obj = ResourceManager.GetObject("left_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap left_normal {
            get {
                object obj = ResourceManager.GetObject("left_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap minimize_normal {
            get {
                object obj = ResourceManager.GetObject("minimize_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1755922612322&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;11643&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M440.507964 511.963431L92.738519 357.277337a63.849154 63.849154 0 0 0-60.045997 0A62.313263 62.313263 0 0 0 0 411.179773v394.723805a62.166988 62.166988 0 0 0 35.54489 56.315978l348.500821 154.905506a64.361117 64.361117 0 0 0 28.377402 6.8018 66.408971 66.408971 0 0 0 31.010356-8.849653 63.264053 63.264053 0 0 0 32.399971-53.975573V565.865867A63.629741 63 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string moduleIcon {
            get {
                return ResourceManager.GetString("moduleIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Npc {
            get {
                object obj = ResourceManager.GetObject("Npc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] NpcWhite {
            get {
                object obj = ResourceManager.GetObject("NpcWhite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ok_hover {
            get {
                object obj = ResourceManager.GetObject("ok_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ok_normal {
            get {
                object obj = ResourceManager.GetObject("ok_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1755091003951&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1042 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;6442&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M581.632 697.344l126.976 0 0 194.56q0 33.792-10.24 58.88t-27.136 40.96-39.424 23.552-48.128 7.68l-452.608 0q-24.576 0-48.128-9.728t-41.472-27.136-29.184-40.96-11.264-52.224l0-706.56q0-24.576 11.776-47.104t30.208-39.936 40.96-28.16 45.056-10.752l449.536 0q26.624 0 50.176 11.776t41.472 29.696 28.16 40.448 10.24 44.032l0 188.416-126.976 0 1.024-195.584-452.6 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1755404127609&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;6193&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M821.043 233.882c-7.065-0.512-13.926 2.048-18.944 7.065s-7.577 11.879-7.065 18.944v520.5c-1.844 27.75-23.86 49.97-51.61 52.019H289.69c-31.028 0-67.072-26.01-67.072-52.02v-58.265c0-26.01 31.027-41.984 62.054-41.984h433.254c7.066 0.512 13.927-2.048 18.944-7.066s7.578-11.878 7.066-18.944V228.864c0.512-26.726-10.445-52.429-30.31-70.349-19.764-18.022-46.388-26 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string reference {
            get {
                return ResourceManager.GetString("reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap right_hover {
            get {
                object obj = ResourceManager.GetObject("right_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap right_normal {
            get {
                object obj = ResourceManager.GetObject("right_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SAOWelcomeTT {
            get {
                object obj = ResourceManager.GetObject("SAOWelcomeTT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1724122928419&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;2893&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M920.5 435.9c-7.6-40.3-36.1-66.8-69.8-66.2h-3.4c-36.6 0-66.3-29.7-66.3-66.3 0-7.8 3.6-19.1 6-24.9 15.4-35.1 3.3-78.1-28.9-100.6l-102-56.9-4.2-2c-31.7-13.7-72.7-5.4-96.4 19.2-15.1 15.6-42.2 33.7-54.6 33.7-12.5 0-39.8-18.5-54.9-34.3-23.6-24.9-62.2-34.4-97.4-19.5l-105.4 57.7-4.2 2.7c-31.7 22-43.8 65.3-28.3 100.1 1.9 4.6 6 16.7 6 24.9 0 36.6-29.7 66.3-66.3 66 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string set_up {
            get {
                return ResourceManager.GetString("set_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap setting_hover {
            get {
                object obj = ResourceManager.GetObject("setting_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap setting_normal {
            get {
                object obj = ResourceManager.GetObject("setting_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1755060932429&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;19756&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M637.256674 18.797246c-24.996338-24.996338-65.590392-24.996338-90.586731 0l-239.964849 239.964849c-24.996338 24.996338-24.996338 65.590392 0 90.586731l31.995314 31.995313c24.996338 24.996338 65.590392 24.996338 90.58673 0l7.998828-7.998828 213.568716 213.368745-7.998828 7.998828c-24.996338 24.996338-24.996338 65.590392 0 90.58673l31.995313 31.995314c24.9 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Stakes {
            get {
                return ResourceManager.GetString("Stakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap top_hover {
            get {
                object obj = ResourceManager.GetObject("top_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap top_normal {
            get {
                object obj = ResourceManager.GetObject("top_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1754590078301&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;8371&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M619.064182 504.57971c91.163561-42.401656 154.766046-133.565217 154.766046-239.569358C773.830228 118.724638 655.10559 0 508.819876 0S243.809524 118.724638 243.809524 265.010352c0 106.004141 63.602484 197.167702 154.766045 239.569358C169.606625 555.461698 0 758.989648 0 1002.799172v21.200828h1017.639752v-21.200828c0-243.809524-169.606625-447.337474-398.575 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string userUid {
            get {
                return ResourceManager.GetString("userUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 伤害 {
            get {
                object obj = ResourceManager.GetObject("伤害", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 伤害白色 {
            get {
                object obj = ResourceManager.GetObject("伤害白色", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 冰魔导师 {
            get {
                object obj = ResourceManager.GetObject("冰魔导师", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 冰魔导师10 {
            get {
                object obj = ResourceManager.GetObject("冰魔导师10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 巨刃守护者 {
            get {
                object obj = ResourceManager.GetObject("巨刃守护者", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 巨刃守护者10 {
            get {
                object obj = ResourceManager.GetObject("巨刃守护者10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 承伤 {
            get {
                object obj = ResourceManager.GetObject("承伤", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 承伤白色 {
            get {
                object obj = ResourceManager.GetObject("承伤白色", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 森语者 {
            get {
                object obj = ResourceManager.GetObject("森语者", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 森语者10 {
            get {
                object obj = ResourceManager.GetObject("森语者10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 治疗 {
            get {
                object obj = ResourceManager.GetObject("治疗", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 治疗白色 {
            get {
                object obj = ResourceManager.GetObject("治疗白色", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 灵魂乐手 {
            get {
                object obj = ResourceManager.GetObject("灵魂乐手", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 灵魂乐手10 {
            get {
                object obj = ResourceManager.GetObject("灵魂乐手10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 皇冠 {
            get {
                object obj = ResourceManager.GetObject("皇冠", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 皇冠白 {
            get {
                object obj = ResourceManager.GetObject("皇冠白", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 神射手 {
            get {
                object obj = ResourceManager.GetObject("神射手", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 神射手10 {
            get {
                object obj = ResourceManager.GetObject("神射手10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 神盾骑士 {
            get {
                object obj = ResourceManager.GetObject("神盾骑士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 神盾骑士10 {
            get {
                object obj = ResourceManager.GetObject("神盾骑士10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 雷影剑士 {
            get {
                object obj = ResourceManager.GetObject("雷影剑士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 雷影剑士10 {
            get {
                object obj = ResourceManager.GetObject("雷影剑士10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 青岚骑士 {
            get {
                object obj = ResourceManager.GetObject("青岚骑士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 青岚骑士10 {
            get {
                object obj = ResourceManager.GetObject("青岚骑士10", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
