//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarResonanceDpsAnalysis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarResonanceDpsAnalysis.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总承伤.
        /// </summary>
        internal static string AlwaysInjuredLabel {
            get {
                return ResourceManager.GetString("AlwaysInjuredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        internal static string ClearButtonLabel {
            get {
                return ResourceManager.GetString("ClearButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人物承伤分析.
        /// </summary>
        internal static string Damage_Taken_Analysis {
            get {
                return ResourceManager.GetString("Damage_Taken_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前伤害.
        /// </summary>
        internal static string Header_Current_Damage {
            get {
                return ResourceManager.GetString("Header_Current_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前治疗.
        /// </summary>
        internal static string Header_Current_Healing {
            get {
                return ResourceManager.GetString("Header_Current_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前 · NPC承伤.
        /// </summary>
        internal static string Header_Current_NpcTaken {
            get {
                return ResourceManager.GetString("Header_Current_NpcTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前承伤.
        /// </summary>
        internal static string Header_Current_Taken {
            get {
                return ResourceManager.GetString("Header_Current_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前伤害.
        /// </summary>
        internal static string Header_DpsStatistics_Subtitle {
            get {
                return ResourceManager.GetString("Header_DpsStatistics_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS伤害统计表.
        /// </summary>
        internal static string Header_DpsStatistics_Title {
            get {
                return ResourceManager.GetString("Header_DpsStatistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全程伤害.
        /// </summary>
        internal static string Header_FullRecord_Damage {
            get {
                return ResourceManager.GetString("Header_FullRecord_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全程治疗.
        /// </summary>
        internal static string Header_FullRecord_Healing {
            get {
                return ResourceManager.GetString("Header_FullRecord_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全程 · NPC承伤.
        /// </summary>
        internal static string Header_FullRecord_NpcTaken {
            get {
                return ResourceManager.GetString("Header_FullRecord_NpcTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全程承伤.
        /// </summary>
        internal static string Header_FullRecord_Taken {
            get {
                return ResourceManager.GetString("Header_FullRecord_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前 · NPC攻击者榜 (NPC:{0}).
        /// </summary>
        internal static string Header_NpcAttackers_Current {
            get {
                return ResourceManager.GetString("Header_NpcAttackers_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全程 · NPC攻击者榜 (NPC:{0}).
        /// </summary>
        internal static string Header_NpcAttackers_FullRecord {
            get {
                return ResourceManager.GetString("Header_NpcAttackers_FullRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害参考.
        /// </summary>
        internal static string Menu_DamageReference {
            get {
                return ResourceManager.GetString("Menu_DamageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公会花名册.
        /// </summary>
        internal static string Menu_GuildRoster {
            get {
                return ResourceManager.GetString("Menu_GuildRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Member Discord Data.
        /// </summary>
        internal static string Menu_GuildMemberDiscordData {
            get {
                return ResourceManager.GetString("Menu_GuildMemberDiscordData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 死亡统计.
        /// </summary>
        internal static string Menu_DeathStatistics {
            get {
                return ResourceManager.GetString("Menu_DeathStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史战斗.
        /// </summary>
        internal static string Menu_HistoricalBattles {
            get {
                return ResourceManager.GetString("Menu_HistoricalBattles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主窗体.
        /// </summary>
        internal static string Menu_MainForm {
            get {
                return ResourceManager.GetString("Menu_MainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组配置.
        /// </summary>
        internal static string Menu_ModuleConfig {
            get {
                return ResourceManager.GetString("Menu_ModuleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打桩模式.
        /// </summary>
        internal static string Menu_PilingMode {
            get {
                return ResourceManager.GetString("Menu_PilingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础设置.
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能日记.
        /// </summary>
        internal static string Menu_SkillDiary {
            get {
                return ResourceManager.GetString("Menu_SkillDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敏捷加持.
        /// </summary>
        internal static string ModuleAttr_AgilityBoost {
            get {
                return ResourceManager.GetString("ModuleAttr_AgilityBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 攻速专注.
        /// </summary>
        internal static string ModuleAttr_AttackSpeedFocus {
            get {
                return ResourceManager.GetString("ModuleAttr_AttackSpeedFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 施法专注.
        /// </summary>
        internal static string ModuleAttr_CastingFocus {
            get {
                return ResourceManager.GetString("ModuleAttr_CastingFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暴击专注.
        /// </summary>
        internal static string ModuleAttr_CriticalFocus {
            get {
                return ResourceManager.GetString("ModuleAttr_CriticalFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精英打击.
        /// </summary>
        internal static string ModuleAttr_EliteStrike {
            get {
                return ResourceManager.GetString("ModuleAttr_EliteStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 专精治疗加持.
        /// </summary>
        internal static string ModuleAttr_ExpertHealingBoost {
            get {
                return ResourceManager.GetString("ModuleAttr_ExpertHealingBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极-伤害叠加.
        /// </summary>
        internal static string ModuleAttr_ExtremeDamageStack {
            get {
                return ResourceManager.GetString("ModuleAttr_ExtremeDamageStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极-绝境守护.
        /// </summary>
        internal static string ModuleAttr_ExtremeDesperateGuardian {
            get {
                return ResourceManager.GetString("ModuleAttr_ExtremeDesperateGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极-急救措施.
        /// </summary>
        internal static string ModuleAttr_ExtremeEmergencyMeasures {
            get {
                return ResourceManager.GetString("ModuleAttr_ExtremeEmergencyMeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极-灵活身法.
        /// </summary>
        internal static string ModuleAttr_ExtremeFlexibleMovement {
            get {
                return ResourceManager.GetString("ModuleAttr_ExtremeFlexibleMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极-生命凝聚.
        /// </summary>
        internal static string ModuleAttr_ExtremeLifeConvergence {
            get {
                return ResourceManager.GetString("ModuleAttr_ExtremeLifeConvergence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极-生命汲取.
        /// </summary>
        internal static string ModuleAttr_ExtremeLifeDrain {
            get {
                return ResourceManager.GetString("ModuleAttr_ExtremeLifeDrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极-生命波动.
        /// </summary>
        internal static string ModuleAttr_ExtremeLifeFluctuation {
            get {
                return ResourceManager.GetString("ModuleAttr_ExtremeLifeFluctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极-全队幸暴.
        /// </summary>
        internal static string ModuleAttr_ExtremeTeamCrit {
            get {
                return ResourceManager.GetString("ModuleAttr_ExtremeTeamCrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 智力加持.
        /// </summary>
        internal static string ModuleAttr_IntelligenceBoost {
            get {
                return ResourceManager.GetString("ModuleAttr_IntelligenceBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸运专注.
        /// </summary>
        internal static string ModuleAttr_LuckFocus {
            get {
                return ResourceManager.GetString("ModuleAttr_LuckFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抵御魔法.
        /// </summary>
        internal static string ModuleAttr_MagicResistance {
            get {
                return ResourceManager.GetString("ModuleAttr_MagicResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抵御物理.
        /// </summary>
        internal static string ModuleAttr_PhysicalResistance {
            get {
                return ResourceManager.GetString("ModuleAttr_PhysicalResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特攻伤害.
        /// </summary>
        internal static string ModuleAttr_SpecialAttackDamage {
            get {
                return ResourceManager.GetString("ModuleAttr_SpecialAttackDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特攻治疗加持.
        /// </summary>
        internal static string ModuleAttr_SpecialHealingBoost {
            get {
                return ResourceManager.GetString("ModuleAttr_SpecialHealingBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 力量加持.
        /// </summary>
        internal static string ModuleAttr_StrengthBoost {
            get {
                return ResourceManager.GetString("ModuleAttr_StrengthBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性分布: .
        /// </summary>
        internal static string ModuleCalc_AttrEffects {
            get {
                return ResourceManager.GetString("ModuleCalc_AttrEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一名搭配.
        /// </summary>
        internal static string ModuleCalc_AttrRanking {
            get {
                return ResourceManager.GetString("ModuleCalc_AttrRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算.
        /// </summary>
        internal static string ModuleCalc_Button1 {
            get {
                return ResourceManager.GetString("ModuleCalc_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除属性.
        /// </summary>
        internal static string ModuleCalc_Button2 {
            get {
                return ResourceManager.GetString("ModuleCalc_Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总属性值:.
        /// </summary>
        internal static string ModuleCalc_EffectsTotal {
            get {
                return ResourceManager.GetString("ModuleCalc_EffectsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标词条和等级（0为默认）[可输入文字索引].
        /// </summary>
        internal static string ModuleCalc_GroupBox1 {
            get {
                return ResourceManager.GetString("ModuleCalc_GroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除词条（与目标词条冲突）[可输入文字索引].
        /// </summary>
        internal static string ModuleCalc_GroupBox3 {
            get {
                return ResourceManager.GetString("ModuleCalc_GroupBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最高属性等级: .
        /// </summary>
        internal static string ModuleCalc_HighestPowerCore {
            get {
                return ResourceManager.GetString("ModuleCalc_HighestPowerCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级：.
        /// </summary>
        internal static string ModuleCalc_InputNumber1_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_InputNumber1_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级：.
        /// </summary>
        internal static string ModuleCalc_InputNumber2_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_InputNumber2_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级：.
        /// </summary>
        internal static string ModuleCalc_InputNumber3_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_InputNumber3_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级：.
        /// </summary>
        internal static string ModuleCalc_InputNumber4_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_InputNumber4_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级：.
        /// </summary>
        internal static string ModuleCalc_InputNumber5_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_InputNumber5_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择模组属性.
        /// </summary>
        internal static string ModuleCalc_Label1 {
            get {
                return ResourceManager.GetString("ModuleCalc_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组列表.
        /// </summary>
        internal static string ModuleCalc_ModuleList {
            get {
                return ResourceManager.GetString("ModuleCalc_ModuleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型选择.
        /// </summary>
        internal static string ModuleCalc_Select1 {
            get {
                return ResourceManager.GetString("ModuleCalc_Select1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型：.
        /// </summary>
        internal static string ModuleCalc_Select1_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_Select1_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除3.
        /// </summary>
        internal static string ModuleCalc_Select10 {
            get {
                return ResourceManager.GetString("ModuleCalc_Select10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除3：.
        /// </summary>
        internal static string ModuleCalc_Select10_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_Select10_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除2.
        /// </summary>
        internal static string ModuleCalc_Select11 {
            get {
                return ResourceManager.GetString("ModuleCalc_Select11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除2：.
        /// </summary>
        internal static string ModuleCalc_Select11_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_Select11_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除1.
        /// </summary>
        internal static string ModuleCalc_Select12 {
            get {
                return ResourceManager.GetString("ModuleCalc_Select12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除1：.
        /// </summary>
        internal static string ModuleCalc_Select12_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_Select12_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性1.
        /// </summary>
        internal static string ModuleCalc_Select2 {
            get {
                return ResourceManager.GetString("ModuleCalc_Select2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性1：.
        /// </summary>
        internal static string ModuleCalc_Select2_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_Select2_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序方式.
        /// </summary>
        internal static string ModuleCalc_Select3 {
            get {
                return ResourceManager.GetString("ModuleCalc_Select3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评分排序.
        /// </summary>
        internal static string ModuleCalc_Select3_Item_SortByScore {
            get {
                return ResourceManager.GetString("ModuleCalc_Select3_Item_SortByScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总属性排序.
        /// </summary>
        internal static string ModuleCalc_Select3_Item_SortByTotalAttr {
            get {
                return ResourceManager.GetString("ModuleCalc_Select3_Item_SortByTotalAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序：.
        /// </summary>
        internal static string ModuleCalc_Select3_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_Select3_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性2.
        /// </summary>
        internal static string ModuleCalc_Select4 {
            get {
                return ResourceManager.GetString("ModuleCalc_Select4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性2：.
        /// </summary>
        internal static string ModuleCalc_Select4_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_Select4_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性3.
        /// </summary>
        internal static string ModuleCalc_Select5 {
            get {
                return ResourceManager.GetString("ModuleCalc_Select5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性3：.
        /// </summary>
        internal static string ModuleCalc_Select5_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_Select5_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性4.
        /// </summary>
        internal static string ModuleCalc_Select6 {
            get {
                return ResourceManager.GetString("ModuleCalc_Select6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性4：.
        /// </summary>
        internal static string ModuleCalc_Select6_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_Select6_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性5.
        /// </summary>
        internal static string ModuleCalc_Select7 {
            get {
                return ResourceManager.GetString("ModuleCalc_Select7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性5：.
        /// </summary>
        internal static string ModuleCalc_Select7_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_Select7_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除5.
        /// </summary>
        internal static string ModuleCalc_Select8 {
            get {
                return ResourceManager.GetString("ModuleCalc_Select8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除5：.
        /// </summary>
        internal static string ModuleCalc_Select8_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_Select8_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除4.
        /// </summary>
        internal static string ModuleCalc_Select9 {
            get {
                return ResourceManager.GetString("ModuleCalc_Select9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除4：.
        /// </summary>
        internal static string ModuleCalc_Select9_Prefix {
            get {
                return ResourceManager.GetString("ModuleCalc_Select9_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组计算器.
        /// </summary>
        internal static string ModuleCalc_Title {
            get {
                return ResourceManager.GetString("ModuleCalc_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 综合评分: .
        /// </summary>
        internal static string ModuleCalc_TotalScore {
            get {
                return ResourceManager.GetString("ModuleCalc_TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        internal static string ModuleCategory_All {
            get {
                return ResourceManager.GetString("ModuleCategory_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 攻击.
        /// </summary>
        internal static string ModuleCategory_Attack {
            get {
                return ResourceManager.GetString("ModuleCategory_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 守护.
        /// </summary>
        internal static string ModuleCategory_Guardian {
            get {
                return ResourceManager.GetString("ModuleCategory_Guardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辅助.
        /// </summary>
        internal static string ModuleCategory_Support {
            get {
                return ResourceManager.GetString("ModuleCategory_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础攻击.
        /// </summary>
        internal static string ModuleName_BasicAttack {
            get {
                return ResourceManager.GetString("ModuleName_BasicAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础治疗.
        /// </summary>
        internal static string ModuleName_BasicHealing {
            get {
                return ResourceManager.GetString("ModuleName_BasicHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础防护.
        /// </summary>
        internal static string ModuleName_BasicProtection {
            get {
                return ResourceManager.GetString("ModuleName_BasicProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卓越攻击.
        /// </summary>
        internal static string ModuleName_ExcellentAttack {
            get {
                return ResourceManager.GetString("ModuleName_ExcellentAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卓越辅助.
        /// </summary>
        internal static string ModuleName_ExcellentHealing {
            get {
                return ResourceManager.GetString("ModuleName_ExcellentHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卓越守护.
        /// </summary>
        internal static string ModuleName_ExcellentProtection {
            get {
                return ResourceManager.GetString("ModuleName_ExcellentProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高性能攻击.
        /// </summary>
        internal static string ModuleName_HighPerformanceAttack {
            get {
                return ResourceManager.GetString("ModuleName_HighPerformanceAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高性能治疗.
        /// </summary>
        internal static string ModuleName_HighPerformanceHealing {
            get {
                return ResourceManager.GetString("ModuleName_HighPerformanceHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高性能守护.
        /// </summary>
        internal static string ModuleName_HighPerformanceProtection {
            get {
                return ResourceManager.GetString("ModuleName_HighPerformanceProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打桩完成,是否上传(排行榜仅供娱乐，请勿恶意上传)
        ///1.如果对自己数据不满意可再次勾选打桩模式重新打桩.
        /// </summary>
        internal static string Msg_PilingComplete {
            get {
                return ResourceManager.GetString("Msg_PilingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打桩时间为3分钟，需注意以下3点:
        ///0.:打桩模式开启后只会记录自己的数据
        ///1.开启后请找协会内最右侧木桩[靠窗的那根]
        ///2.确保战斗计时为0开启
        ///3.如果伤害不满意可关闭打桩模式重新勾选
        ///4.异常数据会被删除
        ///.
        /// </summary>
        internal static string Msg_PilingModeInfo {
            get {
                return ResourceManager.GetString("Msg_PilingModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未获取到UID，请换个地图后再进协会.
        /// </summary>
        internal static string Msg_UidNotFound {
            get {
                return ResourceManager.GetString("Msg_UidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传失败.
        /// </summary>
        internal static string Msg_UploadFail {
            get {
                return ResourceManager.GetString("Msg_UploadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查网络状况，服务器暂时不支持外网上传.
        /// </summary>
        internal static string Msg_UploadFailDetail {
            get {
                return ResourceManager.GetString("Msg_UploadFailDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传成功.
        /// </summary>
        internal static string Msg_UploadSuccess {
            get {
                return ResourceManager.GetString("Msg_UploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先过图一次在点此按钮.
        /// </summary>
        internal static string Notice_ChangeMaps {
            get {
                return ResourceManager.GetString("Notice_ChangeMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承伤.
        /// </summary>
        internal static string NpcTakeDamageLabel {
            get {
                return ResourceManager.GetString("NpcTakeDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打桩模式.
        /// </summary>
        internal static string PilingModeCheckboxLabel {
            get {
                return ResourceManager.GetString("PilingModeCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 神盾骑士.
        /// </summary>
        internal static string Profession_AegisKnight {
            get {
                return ResourceManager.GetString("Profession_AegisKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗灵祈舞_仪刀_仪仗.
        /// </summary>
        internal static string Profession_DarkSpiritDance {
            get {
                return ResourceManager.GetString("Profession_DarkSpiritDance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冰魔导师.
        /// </summary>
        internal static string Profession_FrostMage {
            get {
                return ResourceManager.GetString("Profession_FrostMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 巨刃守护者.
        /// </summary>
        internal static string Profession_HeavyGuardian {
            get {
                return ResourceManager.GetString("Profession_HeavyGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 神射手.
        /// </summary>
        internal static string Profession_Marksman {
            get {
                return ResourceManager.GetString("Profession_Marksman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 涤罪恶火_战斧.
        /// </summary>
        internal static string Profession_PurifyingAxe {
            get {
                return ResourceManager.GetString("Profession_PurifyingAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 灵魂乐手.
        /// </summary>
        internal static string Profession_SoulMusician {
            get {
                return ResourceManager.GetString("Profession_SoulMusician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷影剑士.
        /// </summary>
        internal static string Profession_Stormblade {
            get {
                return ResourceManager.GetString("Profession_Stormblade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷霆一闪_手炮.
        /// </summary>
        internal static string Profession_ThunderHandCannon {
            get {
                return ResourceManager.GetString("Profession_ThunderHandCannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        internal static string Profession_Unknown {
            get {
                return ResourceManager.GetString("Profession_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 森语者.
        /// </summary>
        internal static string Profession_VerdantOracle {
            get {
                return ResourceManager.GetString("Profession_VerdantOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 青岚骑士.
        /// </summary>
        internal static string Profession_WindKnight {
            get {
                return ResourceManager.GetString("Profession_WindKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础设置.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鼠标穿透键：.
        /// </summary>
        internal static string Settings_Input1_Prefix {
            get {
                return ResourceManager.GetString("Settings_Input1_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 透明键：.
        /// </summary>
        internal static string Settings_Input2_Prefix {
            get {
                return ResourceManager.GetString("Settings_Input2_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开关键：.
        /// </summary>
        internal static string Settings_Input3_Prefix {
            get {
                return ResourceManager.GetString("Settings_Input3_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空数据键：.
        /// </summary>
        internal static string Settings_Input4_Prefix {
            get {
                return ResourceManager.GetString("Settings_Input4_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空历史键：.
        /// </summary>
        internal static string Settings_Input5_Prefix {
            get {
                return ResourceManager.GetString("Settings_Input5_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脱战.
        /// </summary>
        internal static string Settings_InputNumber2_Prefix {
            get {
                return ResourceManager.GetString("Settings_InputNumber2_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        internal static string Settings_InputNumber2_Suffix {
            get {
                return ResourceManager.GetString("Settings_InputNumber2_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网卡：.
        /// </summary>
        internal static string Settings_InterfaceComboBox_Prefix {
            get {
                return ResourceManager.GetString("Settings_InterfaceComboBox_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础设置.
        /// </summary>
        internal static string Settings_Label1 {
            get {
                return ResourceManager.GetString("Settings_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS统计伤害显示类型.
        /// </summary>
        internal static string Settings_Label10 {
            get {
                return ResourceManager.GetString("Settings_Label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脱战.
        /// </summary>
        internal static string Settings_Label11 {
            get {
                return ResourceManager.GetString("Settings_Label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络设置.
        /// </summary>
        internal static string Settings_Label2 {
            get {
                return ResourceManager.GetString("Settings_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按键设置.
        /// </summary>
        internal static string Settings_Label3 {
            get {
                return ResourceManager.GetString("Settings_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 战斗设置.
        /// </summary>
        internal static string Settings_Label4 {
            get {
                return ResourceManager.GetString("Settings_Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 换地图是否清空全程统计.
        /// </summary>
        internal static string Settings_Label5 {
            get {
                return ResourceManager.GetString("Settings_Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete删除当前键位.
        /// </summary>
        internal static string Settings_Label6 {
            get {
                return ResourceManager.GetString("Settings_Label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动设置错误时可手动设置.
        /// </summary>
        internal static string Settings_Label7 {
            get {
                return ResourceManager.GetString("Settings_Label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脱战清空为当前统计非全程统计.
        /// </summary>
        internal static string Settings_Label8 {
            get {
                return ResourceManager.GetString("Settings_Label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗体透明度.
        /// </summary>
        internal static string Settings_Label9 {
            get {
                return ResourceManager.GetString("Settings_Label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string Settings_LanguageSelect {
            get {
                return ResourceManager.GetString("Settings_LanguageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害显示.
        /// </summary>
        internal static string Settings_Select2 {
            get {
                return ResourceManager.GetString("Settings_Select2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能伤害分析.
        /// </summary>
        internal static string Skill_Damage_Analysis {
            get {
                return ResourceManager.GetString("Skill_Damage_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能治疗分析.
        /// </summary>
        internal static string Skill_Healing_Analysis {
            get {
                return ResourceManager.GetString("Skill_Healing_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 臂章：.
        /// </summary>
        internal static string SkillDetail_Armband {
            get {
                return ResourceManager.GetString("SkillDetail_Armband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均伤害.
        /// </summary>
        internal static string SkillDetail_AvgPerHit {
            get {
                return ResourceManager.GetString("SkillDetail_AvgPerHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 战力：.
        /// </summary>
        internal static string SkillDetail_CombatPower {
            get {
                return ResourceManager.GetString("SkillDetail_CombatPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暴击率.
        /// </summary>
        internal static string SkillDetail_CritRate {
            get {
                return ResourceManager.GetString("SkillDetail_CritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害分布.
        /// </summary>
        internal static string SkillDetail_Damage_Distribution {
            get {
                return ResourceManager.GetString("SkillDetail_Damage_Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dps/Hps/DTps实时曲线图&quot;.
        /// </summary>
        internal static string SkillDetail_Dps_Hps_DTps_real_time_graph {
            get {
                return ResourceManager.GetString("SkillDetail_Dps/Hps/DTps real-time graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命中次数.
        /// </summary>
        internal static string SkillDetail_HitCount {
            get {
                return ResourceManager.GetString("SkillDetail_HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总承伤.
        /// </summary>
        internal static string SkillDetail_Label1_Total_Damage_Taken {
            get {
                return ResourceManager.GetString("SkillDetail_Label1_Total_Damage_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总伤害.
        /// </summary>
        internal static string SkillDetail_Label1_TotalDamage {
            get {
                return ResourceManager.GetString("SkillDetail_Label1_TotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总治疗.
        /// </summary>
        internal static string SkillDetail_Label1_TotalHealing {
            get {
                return ResourceManager.GetString("SkillDetail_Label1_TotalHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 挨打次数.
        /// </summary>
        internal static string SkillDetail_Label13_HitsTaken {
            get {
                return ResourceManager.GetString("SkillDetail_Label13_HitsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸运次数.
        /// </summary>
        internal static string SkillDetail_Label14_LuckyHits {
            get {
                return ResourceManager.GetString("SkillDetail_Label14_LuckyHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命中次数.
        /// </summary>
        internal static string SkillDetail_Label17_Hits {
            get {
                return ResourceManager.GetString("SkillDetail_Label17_Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害分布.
        /// </summary>
        internal static string SkillDetail_Label19 {
            get {
                return ResourceManager.GetString("SkillDetail_Label19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒伤.
        /// </summary>
        internal static string SkillDetail_Label2_DPS {
            get {
                return ResourceManager.GetString("SkillDetail_Label2_DPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒承伤.
        /// </summary>
        internal static string SkillDetail_Label2_DPS_Taken {
            get {
                return ResourceManager.GetString("SkillDetail_Label2_DPS_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒治疗.
        /// </summary>
        internal static string SkillDetail_Label2_HPS {
            get {
                return ResourceManager.GetString("SkillDetail_Label2_HPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害信息&quot;.
        /// </summary>
        internal static string SkillDetail_Label3 {
            get {
                return ResourceManager.GetString("SkillDetail_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承伤信息.
        /// </summary>
        internal static string SkillDetail_Label3_Damage_Taken_Info {
            get {
                return ResourceManager.GetString("SkillDetail_Label3_Damage_Taken_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 治疗信息.
        /// </summary>
        internal static string SkillDetail_Label3_HealingInfo {
            get {
                return ResourceManager.GetString("SkillDetail_Label3_HealingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暴击率.
        /// </summary>
        internal static string SkillDetail_Label4_Damage_Crit {
            get {
                return ResourceManager.GetString("SkillDetail_Label4_Damage_Crit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暴击率.
        /// </summary>
        internal static string SkillDetail_Label4_Healing_Crit {
            get {
                return ResourceManager.GetString("SkillDetail_Label4_Healing_Crit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大承伤.
        /// </summary>
        internal static string SkillDetail_Label4_Max_Damage_Taken {
            get {
                return ResourceManager.GetString("SkillDetail_Label4_Max_Damage_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸运率.
        /// </summary>
        internal static string SkillDetail_Label5_Damage_Lucky {
            get {
                return ResourceManager.GetString("SkillDetail_Label5_Damage_Lucky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸运率.
        /// </summary>
        internal static string SkillDetail_Label5_Healing_Lucky {
            get {
                return ResourceManager.GetString("SkillDetail_Label5_Healing_Lucky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小承伤.
        /// </summary>
        internal static string SkillDetail_Label5_Min_Damage_Taken {
            get {
                return ResourceManager.GetString("SkillDetail_Label5_Min_Damage_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 普通伤害.
        /// </summary>
        internal static string SkillDetail_Label6_NormalDamage {
            get {
                return ResourceManager.GetString("SkillDetail_Label6_NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暴击伤害.
        /// </summary>
        internal static string SkillDetail_Label7_CritDamage {
            get {
                return ResourceManager.GetString("SkillDetail_Label7_CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸运伤害.
        /// </summary>
        internal static string SkillDetail_Label8_LuckyDamage {
            get {
                return ResourceManager.GetString("SkillDetail_Label8_LuckyDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均伤害.
        /// </summary>
        internal static string SkillDetail_Label9_AvgDamage {
            get {
                return ResourceManager.GetString("SkillDetail_Label9_AvgDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暴击次数.
        /// </summary>
        internal static string SkillDetail_NumberOfCritHits {
            get {
                return ResourceManager.GetString("SkillDetail_NumberOfCritHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 百分比.
        /// </summary>
        internal static string SkillDetail_Percentage {
            get {
                return ResourceManager.GetString("SkillDetail_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按暴击率排序.
        /// </summary>
        internal static string SkillDetail_Select1_Item_SortByCritRate {
            get {
                return ResourceManager.GetString("SkillDetail_Select1_Item_SortByCritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按暴击率排序.
        /// </summary>
        internal static string SkillDetail_Select1_Item_SortByCritRate_Healing {
            get {
                return ResourceManager.GetString("SkillDetail_Select1_Item_SortByCritRate_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按暴击率排序.
        /// </summary>
        internal static string SkillDetail_Select1_Item_SortByCritRate_Taken {
            get {
                return ResourceManager.GetString("SkillDetail_Select1_Item_SortByCritRate_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按伤害排序.
        /// </summary>
        internal static string SkillDetail_Select1_Item_SortByDamage {
            get {
                return ResourceManager.GetString("SkillDetail_Select1_Item_SortByDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按承伤排序.
        /// </summary>
        internal static string SkillDetail_Select1_Item_SortByDamageTaken {
            get {
                return ResourceManager.GetString("SkillDetail_Select1_Item_SortByDamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按秒伤排序S.
        /// </summary>
        internal static string SkillDetail_Select1_Item_SortByDps {
            get {
                return ResourceManager.GetString("SkillDetail_Select1_Item_SortByDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按秒承伤排序.
        /// </summary>
        internal static string SkillDetail_Select1_Item_SortByDpsTaken {
            get {
                return ResourceManager.GetString("SkillDetail_Select1_Item_SortByDpsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按治疗量排序.
        /// </summary>
        internal static string SkillDetail_Select1_Item_SortByHealing {
            get {
                return ResourceManager.GetString("SkillDetail_Select1_Item_SortByHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按命中次数排序.
        /// </summary>
        internal static string SkillDetail_Select1_Item_SortByHitCount {
            get {
                return ResourceManager.GetString("SkillDetail_Select1_Item_SortByHitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按命中次数排序.
        /// </summary>
        internal static string SkillDetail_Select1_Item_SortByHitCount_Healing {
            get {
                return ResourceManager.GetString("SkillDetail_Select1_Item_SortByHitCount_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按受击次数排序.
        /// </summary>
        internal static string SkillDetail_Select1_Item_SortByHitCount_Taken {
            get {
                return ResourceManager.GetString("SkillDetail_Select1_Item_SortByHitCount_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按HPS排序.
        /// </summary>
        internal static string SkillDetail_Select1_Item_SortByHps {
            get {
                return ResourceManager.GetString("SkillDetail_Select1_Item_SortByHps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能占比分布图.
        /// </summary>
        internal static string SkillDetail_Skill_Distribution {
            get {
                return ResourceManager.GetString("SkillDetail_Skill_Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害.
        /// </summary>
        internal static string SkillDetail_SkillDamage {
            get {
                return ResourceManager.GetString("SkillDetail_SkillDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能名.
        /// </summary>
        internal static string SkillDetail_SkillName {
            get {
                return ResourceManager.GetString("SkillDetail_SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS/秒.
        /// </summary>
        internal static string SkillDetail_TotalDps {
            get {
                return ResourceManager.GetString("SkillDetail_TotalDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空枪.
        /// </summary>
        internal static string SubProfession_AirStyle {
            get {
                return ResourceManager.GetString("SubProfession_AirStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格挡.
        /// </summary>
        internal static string SubProfession_Block {
            get {
                return ResourceManager.GetString("SubProfession_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 协奏.
        /// </summary>
        internal static string SubProfession_Concerto {
            get {
                return ResourceManager.GetString("SubProfession_Concerto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鹰弓.
        /// </summary>
        internal static string SubProfession_EagleBow {
            get {
                return ResourceManager.GetString("SubProfession_EagleBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 居合.
        /// </summary>
        internal static string SubProfession_Iai {
            get {
                return ResourceManager.GetString("SubProfession_Iai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 射线.
        /// </summary>
        internal static string SubProfession_IceRay {
            get {
                return ResourceManager.GetString("SubProfession_IceRay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冰矛.
        /// </summary>
        internal static string SubProfession_IceSpear {
            get {
                return ResourceManager.GetString("SubProfession_IceSpear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 愈合.
        /// </summary>
        internal static string SubProfession_Lifebloom {
            get {
                return ResourceManager.GetString("SubProfession_Lifebloom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 光盾.
        /// </summary>
        internal static string SubProfession_LightShield {
            get {
                return ResourceManager.GetString("SubProfession_LightShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月刃.
        /// </summary>
        internal static string SubProfession_MoonBlade {
            get {
                return ResourceManager.GetString("SubProfession_MoonBlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重装.
        /// </summary>
        internal static string SubProfession_Overdrive {
            get {
                return ResourceManager.GetString("SubProfession_Overdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 防盾.
        /// </summary>
        internal static string SubProfession_Protection {
            get {
                return ResourceManager.GetString("SubProfession_Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 狂音.
        /// </summary>
        internal static string SubProfession_RagingSound {
            get {
                return ResourceManager.GetString("SubProfession_RagingSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 岩盾.
        /// </summary>
        internal static string SubProfession_RockShield {
            get {
                return ResourceManager.GetString("SubProfession_RockShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 惩戒.
        /// </summary>
        internal static string SubProfession_Thornlash {
            get {
                return ResourceManager.GetString("SubProfession_Thornlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 狼弓.
        /// </summary>
        internal static string SubProfession_WolfBow {
            get {
                return ResourceManager.GetString("SubProfession_WolfBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换模式.
        /// </summary>
        internal static string SwitchModeButtonLabel {
            get {
                return ResourceManager.GetString("SwitchModeButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置顶.
        /// </summary>
        internal static string Tooltip_AlwaysOnTop {
            get {
                return ResourceManager.GetString("Tooltip_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空当前数据.
        /// </summary>
        internal static string Tooltip_ClearData {
            get {
                return ResourceManager.GetString("Tooltip_ClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小化.
        /// </summary>
        internal static string Tooltip_Minimize {
            get {
                return ResourceManager.GetString("Tooltip_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击切换：单次统计/全程统.
        /// </summary>
        internal static string Tooltip_SwitchSingleTotal {
            get {
                return ResourceManager.GetString("Tooltip_SwitchSingleTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        internal static string Tooltip_SwitchTheme {
            get {
                return ResourceManager.GetString("Tooltip_SwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总伤害.
        /// </summary>
        internal static string TotalDamageLabel {
            get {
                return ResourceManager.GetString("TotalDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总治疗.
        /// </summary>
        internal static string TotalTreatmentLabel {
            get {
                return ResourceManager.GetString("TotalTreatmentLabel", resourceCulture);
            }
        }
    }
}
